title: Abdulla Sajad
description: Software engineer. Kerala, India.
author: Abdulla Sajad
url: "https://neuralbroker.github.io"
baseurl: ""
markdown: kramdown
permalink: /:year/:month/:day/:title/
collections:
  projects:
    output: false
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
